Update list of runtime dependencies in `recipe/meta.yml`
conda-forge/wetterdienst-feedstock pull request #71
Opened 2022-11-28 17:15 UTC by amotl

This patch just follows the suggestions by `regro-cf-autotick-bot` about packages found by source code inspection but not in the meta.yaml vs. packages found in the meta.yaml but not found by source code inspection.

It addresses our discussion at:
- #57

2022-11-28 17:15 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2022-11-28 21:31 UTC, xylar commented
@amotl, I wouldn't make these changes even though the bot suggested them.  It is important that the dependencies are the same as in the original package:
https://github.com/earthobservations/wetterdienst/blob/v0.48.0/pyproject.toml#L91-L117
If there are missing dependencies, you need to report them to the developers rather than just changing them in the conda-forge recipe.  Sometimes the "missing" dependencies are only in tests or code for development, not the package for general use.

2022-11-28 21:51 UTC, amotl commented
Dear @xylar,

thanks for looking into this. Indeed, most of the added dependencies are _optional_ dependencies [^1]. Is there any way to specify them within the Anaconda metadata file?

Otherwise, is the general recommendation to _not_ include them into the baseline `meta.yml`, and let the user select additional/optional packages instead?

With kind regards,
Andreas.

[^1]: https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#optional-dependencies

2022-11-28 22:00 UTC, xylar commented
@amotl, yes, there is a way to handle optional dependencies. It's a little complicated. I'll send you an example tomorrow and we can discuss further.

2022-11-28 22:02 UTC, amotl commented
Thanks. I've just added e7e2e945 to this patch, which updates the list of dependencies to be more sensible as a default choice. If @gutzbenj agrees, I think it will be good to go, without the need to overengineer things.

2022-11-28 22:06 UTC, xylar commented
Okay here's the example
https://github.com/conda-forge/airflow-feedstock/blob/main/recipe/meta.yaml
The extras are separate packages that include the base package and are of the form `<main>-with-<extra>`. This will only work well if extras are grouped together. We don't want a gagillion additional packages. It's only worth it if users really want these extras.

2022-11-28 22:15 UTC, xylar commented
I will look at this tomorrow but even if these are the right dependencies, they are missing version constraints from the original package and they are very important to include. I will make suggestions to #70 and ask for your feedback.

2022-11-28 22:18 UTC, amotl commented
> I will make suggestions to https://github.com/conda-forge/wetterdienst-feedstock/pull/70 and ask for your feedback.

Apologies. I've just merged this, in order to get the release out of the door, without mixing in unrelated changes.

> I will look at this tomorrow but even if these are the right dependencies, they are missing version constraints from the original package and they are very important to include.

Ah. Version pinning for Anaconda? I will be happy to learn more about writing an optimal `meta.yml`. Feel free to submit your suggestions as a patch right away. Thank you already!

2022-11-28 22:47 UTC, xylar commented
@amotl, hmm, I wish you hadn't merged that yet.  The dependencies are not correct in #70 and need to be fixed.  That is a lot harder to do after the fact.  It is also nice to fix at a new release.

2022-11-28 23:00 UTC, gutzbenj approved these changes

2022-11-28 23:14 UTC, xylar requested changes
Please don't merge this until I have a chance to fix several things.

2022-11-29 09:46 UTC, amotl commented
Closing this in favor of #76. Thank you very much, @xylar!

2022-11-29 09:46 UTC, closed without merging

2022-11-29 09:47 UTC, xylar commented on recipe/meta.yaml
> +    - pytz
I'm happy to do that.  These are among the "optional" dependencies.  So we should make a note of that.  Some users may prefer only to have the minimal package but you will know your users better than I do.